library(tidyverse)
library(knitr)
salesTable <- read_csv("/Users/Dennis/data_science/practice_data/SalesTable.csv")
clientTable <- read_csv("/Users/Dennis/data_science/practice_data/ClientTable.csv")
productTable <- read_csv("/Users/Dennis/data_science/practice_data/ProductTable.csv")